### ISSUE TITLE
Incomplete Deobfuscation Issue

### ISSUE THREAD

**Issue by FyberOptic** [immibis/bearded-octo-nemesis#38]
I just keep bothering you!

I noticed a method not get deobfuscated from a 1.2.5 mod a few days ago, but I just created a temporary workaround in my code to call the right one.  But now it's happened with another mod, and the problem is more pronounced.  A wild guess is an inheritance issue based on my own experience with remapping, but who knows.

If you want examples, get buildcraft-client-B-transport-2.2.14.zip, look in BuildCraftTransport.initialize(), for:  

pipeWaterproof = new ItemBuildCraftTexture(DefaultProps.PIPE_WATERPROOF_ID).e(33);

e is supposed to be setIconIndex.

The more pronounced one was RedPowerLogic-2.0pr5b2.zip, in eloraam.logic.BlockLogic.  The constructor has three unmapped methods, and then down in the class itself is an actual method without a deobfuscated name.

I pulled these from Tekkit Classic, btw.

**Comment by master801** [comment]
That issue actually may be from the mappings themselves. Of course this is just an assumption.

**Comment by FyberOptic** [comment]
I thought it might have been initially, but I actually used the mappings to determine what method it was, so I'm less inclined to think so.

**Comment by master801** [comment]
@FyberOptic Hmm.... I'll have to try it myself, then.

**Comment by FyberOptic** [comment]
Holy crap that makes perfect sense, I can't believe I overlooked it.

Thanks for that.  I'll give it a go.

**Comment by immibis** [comment]
@master801 is correct - without seeing the parent mod (probably Buildcraft Core in this case) BON can't know whether ItemBuildCraftTexture.e is an override of Item.e, or a completely separate method.
